### PR TITLE
update timm to latest --> 0.5.4

### PR DESCRIPTION
**Pull request by aelbakry**

### CODE REVIEW

**Comment by aelbakry** [comment]
It seems that version 0.5.4 isnt availaible through conda only pip

**Comment by jayqi** [comment]
Hi @aelbakry. Two things:

1. From the failed build on this PR, we discovered a bug #14 in our build workflow. (Thanks!) The fix (#15) has been merged into the master branch. Can you please merge or rebase the branch for this PR onto the latest changes from master? Otherwise, the build will continue to fail to build the image. 
2. It looks like you are right that `timm v0.5.4` is not available on conda-forge. This is the open PR on the feedstock: https://github.com/conda-forge/timm-feedstock/pull/12. Unfortunately, the feedstock maintainers seem unresponsive and feedstock appears unmaintained. We can try instead installing `timm` using `pip`—you can try moving the `timm` specification to the `pip` section further down in the environment files.

**Review by jayqi — APPROVED** [review]
Thanks for your patience. This looks good to me.

**Comment by aelbakry** [comment]
Thanks @jayqi

**Pull request merged**
